[project]
name = "wcca-unearthed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pybricks>=3.6.1",
    "pybricksdev>=1.1.0",
]
[tool.pyright]
typeCheckingMode = "basic"
